name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: ['master', 'latest']
        tags: [1, 2, 5, 10, 20, 50, 100]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - uses: actions/setup-go@v5

      - uses: actions/cache@v4
        with:
          path: /home/runner/.cache/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - uses: actions/setup-go@v5

      - name: Setup Nightly Build Hugo
        if: ${{ matrix.version == 'master' }}
        run: go install -tags extended github.com/gohugoio/hugo@${{ matrix.version }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        if: ${{ matrix.version != 'master' }}
        with:
          extended: true
          hugo-version: ${{ matrix.version }}

      - run: npx lorem-ipsum-generator -n 1000 --tag-count ${{ matrix.tags }}

      - name: Build
        run: hugo --minify | npx hugo-metrics-parser
